### ISSUE TITLE
the IoU-Loss, Iou-Aware-Loss and final confidence in PPYOLO？ 

### ISSUE THREAD

**Issue by LLeeSG** [PaddlePaddle/PaddleDetection#1858] opened 2020-12-09 14:53 UTC
from the paper, we know that IoU-Loss and Iou-Aware-Loss (adopt BCE loss) are both used as additional loss to orig box-regression (adopt L1 loss) to improve  the locate accuracy and IoU of  predicted box.  but in my train process, I can rarely see the decrease of IoU-Loss or Iou-Aware-Loss (as follow pic shows).  

![loss](https://user-images.githubusercontent.com/16949144/101708856-1a5be680-3ac9-11eb-922c-5c0aba85f557.png)

so: 
1. how can I reduce the IoU-Loss and Iou-Aware-Loss in PPYOLO？I've tried increasing  the loss_weight of IouLoss and IouAwareLoss in ppyolo.yml and re-cluster the anchor box but didn't get promotion obviously. 
2. what's the role of config item "loss_weight"?
3. while the total  loss is getting decrease and AP increasing, but the final detection confidence shows a big decrease, almost around 0.5 (as follow pic shows), why?
![20201104 15000 pdparams(AP50=35 8) infer result](https://user-images.githubusercontent.com/16949144/101709096-c998bd80-3ac9-11eb-8bdb-f38a4ab6a347.jpg)

**Comment by willthefrog** [comment] 2020-12-10 02:14
1. my hunch is that it could be dataset specific, dataset with few samples or lot of smaller targets could pose difficulty for the IoU related losses, larger dataset and longer training schedule may somewhat alleviate this.
2. just as the name indicates, factor that the loss is to be multiplied by.
3. confidence is objectiveness * predicted_iou * class_score, if the iou is small, confidence will be small too.

@heavengate maybe you would have more input on this?

**Comment by LLeeSG** [comment] 2020-12-10 03:15
> 1. my hunch is that it could be dataset specific, dataset with few samples or lot of smaller targets could pose difficulty for the IoU related losses, larger dataset and longer training schedule may somewhat alleviate this.
> 2. just as the name indicates, a factor that the loss is multiplied by.
> 3. confidence is `objectiveness * predicted_iou * class_score`, if the iou is small, confidence will be small too.
> 
> @heavengate maybe you would have more input on this?

Yep, I wanna promote the iou performance to get better confidence! Below is the cluster/loss of new dataset compared with COCO(labed  'orig'), it's obvious that  the new  cluster is more suitable so that better performace is  expected, but the loss seems not to be good enough.

![k-mean Cluster vs orig](https://user-images.githubusercontent.com/16949144/101716800-04eeb880-3ad9-11eb-8266-e58e3c5b3fcf.png)
![2020-12-10_110951](https://user-images.githubusercontent.com/16949144/101716805-08823f80-3ad9-11eb-8bf1-6bffe6c71b5c.jpg)

**Comment by willthefrog** [comment] 2020-12-10 05:50
makes sense, looks like the cluster leans towards the smaller end, you may wanna check the [iou losses](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/ppdet/modeling/losses/yolo_loss.py#L219) of the different heads.
if losses  are smaller for heads with higher resolution inputs, then maybe the problem is simply too hard  at lower resolution.

**Comment by LLeeSG** [comment] 2020-12-10 08:07
> makes sense, looks like the cluster leans towards the smaller end, you may wanna check the [iou losses](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/ppdet/modeling/losses/yolo_loss.py#L219) of the different heads.
> if losses are smaller for heads with higher resolution inputs, then maybe the problem is simply too hard at lower resolution.

as u mentioned "confidence is objectiveness * predicted_iou * class_score", I wanna see what exactly each value of  objectiveness, predicted_iou, class_score is. So I debug into the infer process till met Lib\site-packages\paddle\fluid\executor.py Line 1313: 

- self._default_executor.run(program.desc, scope, 0, True, True,  fetch_var_name)

this line returns the predict bbox including the final confidence, but I cant step into it so the composition of final confidence still keep in hidden, any tips to figure it out? 3q~

**Comment by willthefrog** [comment] 2020-12-11 10:14
maybe add a couple of `paddle.fluid.layers.Print` statements [here](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/ppdet/modeling/losses/yolo_loss.py#L219)

**Comment by LLeeSG** [comment] 2020-12-13 09:44
> maybe add a couple of `paddle.fluid.layers.Print` statements [here](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/ppdet/modeling/losses/yolo_loss.py#L219)

it works! thanks a lot! 
but more that print it, I want to save the result for further analyze. I tried scope().find_var('transpose_0.tmp_0') but returns None.
So how to save it?

**Comment by willthefrog** [comment] 2020-12-14 01:46
you can add them to`fetch_list` [here](https://github.com/PaddlePaddle/PaddleDetection/blob/master/tools/train.py#L248)

**Comment by LLeeSG** [comment] 2020-12-14 08:04
> you can add them to`fetch_list` [here](https://github.com/PaddlePaddle/PaddleDetection/blob/master/tools/train.py#L248)

it helps a lot for debuging, thanks very much!

**Comment by willthefrog** [comment] 2020-12-14 08:32
glad that it worked for you. 
I'm gonna close this issue for now, feel free to reopen it if you have further questions.

**Closed by willthefrog** 2020-12-14 08:32 UTC
